gmcp_bundle_tester:
    resource: "@GMCPBundleTesterBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

triangle_calculate:
    path: /triangle
    defaults: { _controller: GMCPBundleTesterBundle:Triangle:calculate }